import { test, expect } from '@playwright/test'
import { mockApi, accountId } from './fixtures'

test('login existente, restauração da sessão e logout real', async ({ page }) => {
  const state = await mockApi(page, { authenticated: false })
  await page.goto('/dashboard')
  await expect(page).toHaveURL(/\/login$/)
  await page.getByLabel('E-mail', { exact: true }).fill('paula@example.com')
  await page.getByLabel('Senha', { exact: true }).fill('senha-ficticia')
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Configurações', exact: true }).click()
  await expect(page.getByText('paula@example.com')).toBeVisible()
  await page.getByRole('button', { name: 'Sair da conta' }).click()
  await expect(page).toHaveURL(/\/login$/)
  expect(state.requests.some((request) => request.path === '/auth/logout' && request.method === 'POST')).toBeTruthy()
  expect(await page.evaluate(() => localStorage.length)).toBe(0)
  expect(state.unexpected).toEqual([])
  expect(state.runtimeErrors).toEqual([])
})

test('dashboard, busca por documento com debounce, filtros, paginação e detalhes acessíveis', async ({ page }) => {
  const state = await mockApi(page)
  await page.goto('/dashboard')
  await expect(page.getByRole('button', { name: 'Ver detalhes de Maria Fictícia' })).toBeVisible()
  await expect(page.getByText('123.456.789-00', { exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true })
  await page.getByRole('link', { name: 'Clientes', exact: true }).click()
  await page.getByRole('button', { name: 'Próxima página' }).click()
  await expect(page).toHaveURL(/page=2/)
  await expect(page.getByText('Mostrando 21 a 25 de 25 clientes')).toBeVisible()
  const baseline = state.requests.filter((request) => request.path === '/customers').length
  await page.getByLabel('Buscar cliente', { exact: true }).pressSequentially('123.456.789-00', { delay: 20 })
  await expect(page.getByLabel('Buscar cliente', { exact: true })).toHaveValue('123.456.789-00')
  await expect(page.getByText('Mostrando 1 a 1 de 1 clientes')).toBeVisible()
  expect(state.requests.filter((request) => request.path === '/customers').length - baseline).toBeLessThanOrEqual(2)
  await page.getByRole('button', { name: 'Ver detalhes de Maria Fictícia' }).click()
  const drawer = page.getByRole('dialog', { name: 'Detalhes do cliente' })
  await expect(drawer).toBeVisible()
  await expect(drawer.getByText('123.456.789-00', { exact: true })).toBeVisible()
  await expect(drawer.getByRole('link', { name: 'Abrir no WhatsApp' })).toHaveAttribute('href', 'https://wa.me/5511999999999')
  await expect(drawer.getByRole('link', { name: 'Abrir no WhatsApp' })).toHaveAttribute('rel', 'noopener noreferrer')
  await page.screenshot({ path: 'test-results/customer-drawer.png' })
  await page.keyboard.press('Escape')
  await expect(drawer).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Ver detalhes de Maria Fictícia' })).toBeFocused()
  await page.getByRole('button', { name: 'Limpar', exact: true }).click()
  await page.getByRole('button', { name: 'Sem telefone', exact: true }).click()
  await expect(page.getByText('Mostrando 1 a 12 de 12 clientes')).toBeVisible()
  await expect(page.locator('.customer-table a[href^="https://wa.me/"]')).toHaveCount(0)
  await page.getByLabel('Conta/CNPJ', { exact: true }).selectOption(accountId)
  await expect(page).toHaveURL(new RegExp(`marketplaceAccountId=${accountId}`))
  expect(state.requests.filter((request) => request.path === '/customers' && new URLSearchParams(request.search).get('limit') === '20').every((request) => !new URLSearchParams(request.search).has('platform'))).toBeTruthy()
  expect(state.unexpected).toEqual([])
})

test('importação bloqueia duplo envio entre páginas e mostra resumo parcial', async ({ page }) => {
  const state = await mockApi(page, { importDelay: 1500 })
  await page.goto('/imports')
  await page.getByLabel('Data inicial', { exact: true }).fill('2026-09-01')
  await page.getByLabel('Data final', { exact: true }).fill('2026-09-30')
  await page.getByRole('button', { name: 'Importar clientes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Importando clientes...' })).toBeDisabled()
  await page.getByRole('link', { name: 'Clientes', exact: true }).click()
  await page.getByRole('link', { name: 'Importações', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Resultado da importação' })).toBeVisible()
  await expect(page.locator('.import-result').getByText('Concluída com erros', { exact: true })).toBeVisible()
  expect(state.requests.filter((request) => request.path === '/imports/mercadolivre')).toHaveLength(1)
  expect(state.unexpected).toEqual([])
})

test('estados vazio, erro recuperável e sessão expirada', async ({ page }) => {
  const state = await mockApi(page, { empty: true })
  state.customerFailures = Infinity
  await page.goto('/customers')
  await expect(page.getByRole('alert')).toBeVisible()
  state.customerFailures = 0
  await page.getByRole('button', { name: 'Tentar novamente' }).click()
  await expect(page.getByRole('heading', { name: 'Nenhum cliente encontrado' })).toBeVisible()
  await page.getByRole('link', { name: 'Contas Integradas', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Nenhuma conta conectada' })).toBeVisible()
  state.expired = true
  await page.getByRole('link', { name: 'Clientes', exact: true }).click()
  await expect(page).toHaveURL(/\/login$/)
  expect(state.unexpected).toEqual([])
})

test('mobile e tablet mantêm menu, tabela contida e drawer utilizáveis', async ({ page }) => {
  await mockApi(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/customers')
  await expect(page.getByRole('button', { name: 'Ver detalhes de Maria Fictícia' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: 'test-results/customers-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Abrir menu' }).click()
  await expect(page.getByRole('dialog', { name: 'Navegação' })).toBeVisible()
  await page.getByRole('link', { name: 'Dashboard', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.setViewportSize({ width: 900, height: 1000 })
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible()
  await expect.poll(() => page.locator('.summary-grid').evaluate((element) => getComputedStyle(element).gridTemplateColumns.split(' ').length)).toBe(2)
  await page.screenshot({ path: 'test-results/dashboard-tablet.png', fullPage: true })
  await page.getByRole('button', { name: 'Ver detalhes de Maria Fictícia' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('contas mostram retorno OAuth, confirmam desconexão e iniciam autorização por navegação', async ({ page }) => {
  const state = await mockApi(page)
  await page.goto('/?mercadolivre=success')
  await expect(page).toHaveURL(/\/marketplace-accounts$/)
  await expect(page.getByText('Conta do Mercado Livre conectada com sucesso.')).toBeVisible()
  page.once('dialog', (dialog) => dialog.dismiss())
  await page.getByRole('button', { name: 'Desconectar conta', exact: true }).click()
  expect(state.requests.filter((request) => request.method === 'DELETE')).toHaveLength(0)
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Desconectar conta', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Nenhuma conta conectada' })).toBeVisible()
  expect(state.requests.filter((request) => request.method === 'DELETE')).toHaveLength(1)
  await page.getByRole('button', { name: 'Conectar Mercado Livre', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: 'Autorização simulada' })).toBeVisible()
  expect(state.oauthNavigation).toBeTruthy()
  expect(state.unexpected).toEqual([])
  expect(state.runtimeErrors).toEqual([])
})
